[package]
name = "spartan"
version = "0.1.0"
authors = ["JamisonHubbard <jhubbard956@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
"name" = "lexer"
"path" = "lexer/lib.rs"